# Generated by Django 4.0.3 on 2022-04-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0006_alter_measurement_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='photo',
            field=models.ImageField(null=True, upload_to='sensors_photo/<built-in method today of type object at 0x913920>'),
        ),
    ]
